version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y sshpass
      - mvn -v

  build:
    commands:
      - echo "Building Spring Boot Application..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "JAR files in target:"
      - ls -la target
      - JAR_NAME=$(ls target/*.jar | head -n 1 | xargs -n 1 basename)
      - echo "Detected JAR: $JAR_NAME"
      - sshpass -p "$EC2_PASS" scp -o StrictHostKeyChecking=no target/$JAR_NAME $EC2_USER@$EC2_HOST:/home/$EC2_USER/app/$JAR_NAME
      - sshpass -p "$EC2_PASS" ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "export JAR_NAME=$JAR_NAME && bash /home/$EC2_USER/deploy.sh"

artifacts:
  files:
    - target/*.jar
