version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y sshpass
      - mvn -v
  build:
    commands:
      - echo "Building Spring Boot Application..."
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Processing JAR and Deploying..."
      - |
        # Find the JAR and store it in a local shell variable
        JAR_PATH=$(ls target/*.jar | head -n 1)
        JAR_NAME=$(basename "$JAR_PATH")
        echo "Detected JAR: $JAR_NAME"
        
        # Upload JAR to EC2
        sshpass -p "${EC2_PASS}" scp -o StrictHostKeyChecking=no "$JAR_PATH" "${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/app/$JAR_NAME"
        
        # Trigger deployment script
        sshpass -p "${EC2_PASS}" ssh -o StrictHostKeyChecking=no "${EC2_USER}@${EC2_HOST}" "bash /home/${EC2_USER}/deploy.sh $JAR_NAME"

artifacts:
  files:
    - 'target/*.jar'
  discard-paths: yes
