version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y sshpass
      - mvn -v

  build:
    commands:
      - echo "Building Spring Boot Application..."
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo "Listing target folder..."
      - ls -la target
      - echo "Detecting JAR file..."
      - "JAR_NAME=$(ls target/*.jar | head -n 1 | xargs -n 1 basename)"
      - echo "Detected JAR: $JAR_NAME"
      - echo "Uploading JAR to EC2..."
      - sshpass -p ${EC2_PASS} scp -o StrictHostKeyChecking=no target/$JAR_NAME ${EC2_USER}@${EC2_HOST}:/home/${EC2_USER}/app/$JAR_NAME
      - echo "Triggering deploy.sh on EC2..."
      - sshpass -p ${EC2_PASS} ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} "bash /home/${EC2_USER}/deploy.sh $JAR_NAME"

artifacts:
  files:
    - target/*.jar
